---

- name: ORACLE_INSTANT_CLIENT | Check that the packages needed for installing are present
  apt:
    name: "{{ instant_client_needed_packages }}"
    state: present

- name: ORACLE_INSTANT_CLIENT | Download basic package
  get_url:
    url: "{{ instant_client_basic_url }}"
    dest: "{{ instant_client_basic_package_path }}"

- name: ORACLE_INSTANT_CLIENT | Download devel package
  get_url:
    url: "{{ instant_client_devel_url }}"
    dest: "{{ instant_client_devel_package_path }}"
  when: instant_client_devel_install

- name: ORACLE_INSTANT_CLIENT | Download sqlplus package
  get_url:
    url: "{{ instant_client_sqlplus_url }}"
    dest: "{{ instant_client_sqlplus_package_path }}"

- name: ORACLE_INSTANT_CLIENT | Extract basic package into installation folder
  unarchive:
    src: "{{ instant_client_basic_package_path }}"
    dest: "{{ instant_client_extract_path }}"
    remote_src: True

- name: ORACLE_INSTANT_CLIENT | Extract devel package into installation folder
  unarchive:
    src: "{{ instant_client_devel_package_path }}"
    dest: "{{ instant_client_extract_path }}"
    remote_src: True
  when: instant_client_devel_install

- name: ORACLE_INSTANT_CLIENT | Extract sqlplus package into installation folder
  unarchive:
    src: "{{ instant_client_sqlplus_package_path }}"
    dest: "{{ instant_client_extract_path }}"
    remote_src: True

- name: ORACLE_INSTANT_CLIENT | Simbolic link to installation folder
  file:
   src: "{{ instant_client_root_path }}_{{ instant_client_version[0:2] }}_{{ instant_client_version[3] }}"
   dest: "{{ instant_client_root_path }}"
   state: link

- name: ORACLE_INSTANT_CLIENT | Copy libraries path file
  template:
    src: instant-client-libs.conf.j2
    dest: /etc/ld.so.conf.d/instant-client-libs.conf
    mode: 0644
  notify: update libraries

- name: ORACLE_INSTANT_CLIENT | Simbolic link to sqlplus
  file:
   src: "{{ instant_client_root_path }}/sqlplus"
   dest: "/usr/bin/sqlplus"
   state: link
